# Generated by Django 5.0 on 2025-12-28 22:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_pages_scraped', models.IntegerField(default=0)),
                ('total_records_extracted', models.IntegerField(default=0)),
                ('total_records_loaded', models.IntegerField(default=0)),
                ('log_messages', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Trabajo de Scraping',
                'verbose_name_plural': 'Trabajos de Scraping',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('etiqueta', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('combustible', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('transmision', models.CharField(max_length=50)),
                ('anunciante', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('scraping_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.scrapingjob')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
                'db_table': 'tbl_auto_raw_taller',
                'ordering': ['-fecha'],
            },
        ),
    ]
