# Generated by Django 5.0 on 2025-12-28 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('combustible', models.CharField(max_length=50)),
                ('transmision', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_predicho', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
